### ISSUE TITLE
Getting an error following update to Paper 1.20.6

### ISSUE THREAD

**Issue by FireController1847** [Tanguygab/PlayerList-PlaceholderAPI-Expansion#11]
Seems like the common version checking issue that's been plaguing these recent updates, but I'm not sure.
```
> papi reload
[13:51:54 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[13:51:54 INFO]: [PlaceholderAPI] Fetching available expansion information...
[13:51:55 INFO]: [PlaceholderAPI] Successfully registered external expansion: formatter [2.2.2]
[13:51:55 INFO]: [PlaceholderAPI] Successfully registered external expansion: player [2.0.2]
[13:51:55 INFO]: [PlaceholderAPI] Successfully registered external expansion: checkitem [2.7.1]
[13:51:55 INFO]: [PlaceholderAPI] Successfully registered external expansion: playerlist [3.0.7]
[13:51:55 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
[13:51:55 WARN]:        at com.extendedclip.papi.expansion.server.ServerExpansion.<init>(ServerExpansion.java:65)
[13:51:55 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source)
[13:51:55 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
[13:51:55 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
[13:51:55 WARN]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.createExpansionInstance(LocalExpansionManager.java:453)
[13:51:55 WARN]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:173)
[13:51:55 WARN]:        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[13:51:55 WARN]:        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[13:51:55 WARN]:        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[13:51:55 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[13:51:55 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[13:51:55 WARN]:        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
[13:51:55 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[13:51:55 WARN]:        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
[13:51:55 WARN]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$4(LocalExpansionManager.java:366)
[13:51:55 WARN]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.util.Futures.lambda$null$0(Futures.java:46)
[13:51:55 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[13:51:55 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[13:51:55 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699)
[13:51:55 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467)
[13:51:55 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571)
[13:51:55 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231)
[13:51:55 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[13:51:55 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[13:51:55 INFO]: [PlaceholderAPI] Successfully registered external expansion: server [2.6.0]
[13:51:55 INFO]: [PAPI] [Javascript-Expansion] 3 scripts loaded!
[13:51:55 INFO]: [PlaceholderAPI] Successfully registered external expansion: javascript [2.1.2]
[13:51:55 INFO]: [PlaceholderAPI] Successfully registered external expansion: world [1.2.2]
[13:51:55 INFO]: [PlaceholderAPI] Successfully registered external expansion: random [1.0.0]
[13:51:55 INFO]: [PlaceholderAPI] Successfully registered external expansion: localtime [1.2]
[13:51:55 INFO]: [PlaceholderAPI] Successfully registered external expansion: math [2.0.2]
[13:51:55 INFO]: 10 placeholder hook(s) registered!
```

My /version command output:
```
> version
[13:53:20 INFO]: Checking version, please wait...
[13:53:22 INFO]: This server is running Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-223 (MC: 1.20.2)
```

**Comment by Tanguygab** [comment]
unrelated to my expansion, it's from the Server expansion
![image](https://github.com/Tanguygab/PlayerList-PlaceholderAPI-Expansion/assets/45695833/a6cb6c0c-9ad4-4a67-a3ec-5aa683565020)
Make sure you're using the latest version of the expansion, redownload it just in case with /papi ecloud download Server
If the error is still there after that, report it there https://github.com/PlaceholderAPI/Server-Expansion/issues

**Comment by FireController1847** [comment]
Ah! Silly me. I assumed it was yours since it came right after it, and I missed the "ServerExpansion" line due to assuming it was a PlaceholderAPI function haha. I'll look more carefully next time. Thank you!!

**Comment by FireController1847** [comment]
Ok, sorry, I don't want to open another issue, and maybe I'm being dumb and have missed something on the Wiki, but is it possible to parse using the new update without a player (or viewer?) I was previously using this with my Discord plugin to add a command where players could see all online players, but when I `papi parse` with a `--null` for the viewer, it throws an error:

```
[14:52:10 WARN]: Unexpected exception while parsing console command "papi parse --null %playerlist_online_list%"
org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.11.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:986) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:971) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:521) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:468) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.OfflinePlayer.getName()" because "viewer" is null
        at io.github.tanguygab.playerlistexpansion.PlayerList.getList(PlayerList.java:56) ~[?:?]
        at io.github.tanguygab.playerlistexpansion.PlayerList.getText(PlayerList.java:30) ~[?:?]
        at io.github.tanguygab.playerlistexpansion.PlayerListExpansion.onRequest(PlayerListExpansion.java:105) ~[?:?]
        at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6.jar:?]
        at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.6.jar:?]
        at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.commands.impl.local.CommandParse.evaluateParseSingular(CommandParse.java:118) ~[PlaceholderAPI-2.11.6.jar:?]
        at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.commands.impl.local.CommandParse.evaluate(CommandParse.java:57) ~[PlaceholderAPI-2.11.6.jar:?]
        at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.commands.PlaceholderCommandRouter.onCommand(PlaceholderCommandRouter.java:114) ~[PlaceholderAPI-2.11.6.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 9 more
```

The old way I used to do it was so: `%playerlist_online,normal,yes,list%`

**Comment by Tanguygab** [comment]
you can but it depends on which filters you use, if you jave the CANSEE filter it won't work

I could try to make it ignore the filter if the player is null, but I won't be home for the weekend so won't be able to do it until next week
