### ISSUE TITLE
i have this error recently

### ISSUE THREAD

**Issue by frogglen** [Tanguygab/PlayerList-PlaceholderAPI-Expansion#4]
```
[22:13:49 WARN]: Exception in thread "DiscordSRV - Presence Updater" java.lang.NullPointerException: Cannot invoke "org.bukkit.OfflinePlayer.getName()" because "player" is null
[22:13:49 WARN]:        at io.github.tanguygab.playerlistexpansion.subtype.Permission.getText(Permission.java:21)
[22:13:49 WARN]:        at io.github.tanguygab.playerlistexpansion.playerlist.OnlinePlayerList.getText(OnlinePlayerList.java:21)
[22:13:49 WARN]:        at io.github.tanguygab.playerlistexpansion.PlayerListExpansion.onRequest(PlayerListExpansion.java:52)
[22:13:49 WARN]:        at PlaceholderAPI-2.11.3-DEV-160.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[22:13:49 WARN]:        at PlaceholderAPI-2.11.3-DEV-160.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[22:13:49 WARN]:        at DiscordSRV-Build-1.26.0-SNAPSHOT-525b004.jar//github.scarsz.discordsrv.util.PlaceholderUtil.replacePlaceholders(PlaceholderUtil.java:48)
[22:13:49 WARN]:        at DiscordSRV-Build-1.26.0-SNAPSHOT-525b004.jar//github.scarsz.discordsrv.util.PlaceholderUtil.replacePlaceholders(PlaceholderUtil.java:41)
[22:13:49 WARN]:        at DiscordSRV-Build-1.26.0-SNAPSHOT-525b004.jar//github.scarsz.discordsrv.objects.threads.PresenceUpdater.run(PresenceUpdater.java:80)
```

**Comment by Tanguygab** [comment]
I'm guessing you're using the placeholder in DiscordSRV? try to replace `no` with `yes` in the placeholder

**Comment by frogglen** [comment]
> I'm guessing you're using the placeholder in DiscordSRV? try to replace `no` with `yes` in the placeholder

yes that was the problem, thanks
